apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       —name: demo
          image: fr13drich/demo:v1.0.0
          ports:
           —containerPort: 80