# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.5.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  lint:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If your requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: Run pylint
          # This assumes pytest is installed via the install-package step above
          command: pylint app.py
  dockerize:
    docker:
      - image: cimg/python:3.10.2 
    steps:
      - checkout
      - run:
          name: createVenv
          command: |
            make setup
            #python3 -m venv ~/demoImage &&
            #source ~/demoImage/bin/activate
      - run:
          name: installSoftware
          command: |
            make install
            #pip3 install --upgrade pip &&
            #pip3 install -r requirements.txt
      - run:
          name: buildImage
          command: docker build --tag=demoImage . 
      - run:
          name: CreateDockerpath
          command: |
            dockerpath=fr13drich/demo
      - run:
          name: Authenticate&tag
          command: |
            echo "Docker ID and Image: $dockerpath"
            docker login
            docker tag demo fr13drich/demo:v1.0.0
      - run:
          name: push
          command: docker push fr13drich/demo:v1.0.0
            
  
# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  demo:
    # Inside the workeeow, you define the jobs you want to run.
    jobs:
      - lint
      - dockerize:
          requires:
            - lint
