# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.5.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  lint:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If your requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: Run pylint
          # This assumes pytest is installed via the install-package step above
          command: pylint app.py
  buildImage:
    docker:
      - image: cimg/python:3.10.2 
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: createVenv
          command: |
            make setup
            #python3 -m venv ~/demo &&
            #source ~/demo/bin/activate
      - run:
          name: installSoftware
          command: |
            make install
            #pip3 install --upgrade pip &&
            #pip3 install -r requirements.txt
#        - run:
#           name: startDocker
#           command: |
              # systemctl stop docker
              # cd /var/lib/docker
#               sudo rm -rf /var/lib/docker/*
#               sudo mkdir -p /var/lib/docker/devicemapper/devicemapper
#               sudo dd if=/dev/zero of=/var/lib/docker/devicemapper/devicemapper/data bs=1G count=0 seek=250
              # systemctl start docker
#               sudo dockerd
      - run:
          name: buildImage
          command: |
              docker build --tag=demo . 
  pushImage:
    docker:
      - image: cimg/python:3.10.2 # python:3.7-alpine3.11
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install awscli
          command: |
            pip3 install --upgrade pip 
            pip3 install --no-cache-dir awscli 
      - run:
          name: CreateDockerpath
          command: |
            dockerpath=fr13drich/demo
      - run:
          name: Authenticate&tag
          command: |
            # for dockerhub:
            # docker login -u ${dockerhubusername} -p ${dockerhubpassword}
            # docker tag demo ${dockerhubusername}/demo:v1.0.0
            # for ECR:
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 928015429973.dkr.ecr.us-east-1.amazonaws.com
            docker images
            docker tag demo 928015429973.dkr.ecr.us-east1.amazonaws.com/demo:v1.0.0
      - run:
          name: push
          command: docker push public.ecr.aws/z4a6j9j4/demo # ${dockerhubusername}/demo:v1.0.0
  createInfra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "aws stack"
          command:  |
            aws cloudformation create-stack \
            --template-body file://eks.yml \
            --parameters file://eks.json \
            --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" \
            --stack-name demo \
            --region us-east-1
      - run:
          name: "sleep"
          command: sleep 480 # wait 8' for the cluster to be created
          
  deploy:
    docker:
      - image: cimg/python:3.10.2 # d3fk/kubectl # amazon/aws-cli
    steps:
      - checkout
      - run: 
          name : "sleep"
          command: sleep 420
      - run:
          name: "deploy"
          command: |
            kubectl get nodes
            kubectl create deploy demo --image=fr13drich/demo:v1.0.0
            kubectl get deploy,rs,svc,pods
            mypod=`kubectl get pods --no-headers=true | cut -f 1 -d " "`
            kubectl port-forward pod/$mypod --address 0.0.0.0 80:80
# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  demo:
    jobs:
      - lint
      - buildImage:
          requires:
            - lint
      - pushImage:
          requires:
            - buildImage
      - createInfra:
          requires:
            - pushImage
      - deploy:
          requires:
            - createInfra
            